/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id_details_extractor;

import java.time.LocalDate;
import java.time.Period;
import javax.swing.ImageIcon;

/**
 *
 * @author Shady Emad
 */
public class ID_Extractor extends javax.swing.JFrame {

    /**
     * Creates new form ID
     */
    public ID_Extractor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        j_gender = new javax.swing.JTextField();
        j_date_of_birth = new javax.swing.JTextField();
        j_ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        j_baby_Number = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        j_age = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        j_city_of_birth = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        j_date_of_retirement = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        j_wrong_id = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_gender.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel2.add(j_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 186, 40));

        j_date_of_birth.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel2.add(j_date_of_birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 168, 40));

        j_ID.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jPanel2.add(j_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 300, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gender");
        jLabel3.setToolTipText("");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Date of birth");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 140, 41));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 110, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Baby No.");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 190, 40));

        j_baby_Number.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        j_baby_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_baby_NumberActionPerformed(evt);
            }
        });
        jPanel2.add(j_baby_Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 186, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Age");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 150, 41));

        j_age.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        j_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_ageActionPerformed(evt);
            }
        });
        jPanel2.add(j_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 168, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("City of birth");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 160, 37));

        j_city_of_birth.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        j_city_of_birth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_city_of_birthActionPerformed(evt);
            }
        });
        jPanel2.add(j_city_of_birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 168, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Date of retirement");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 160, 40));

        j_date_of_retirement.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        j_date_of_retirement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_date_of_retirementActionPerformed(evt);
            }
        });
        jPanel2.add(j_date_of_retirement, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 186, 40));

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 110, 30));

        j_wrong_id.setBackground(new java.awt.Color(255, 51, 51));
        j_wrong_id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        j_wrong_id.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(j_wrong_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 260, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id_details_extractor/background.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 550));

        jMenu2.setText("Click to Follow Me");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id_details_extractor/facebook copy.png"))); // NOI18N
        jMenuItem1.setText("ShaadyEmad");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id_details_extractor/instagram copy.jpg"))); // NOI18N
        jMenuItem2.setText("ShaadyEmad");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id_details_extractor/twitter copy.png"))); // NOI18N
        jMenuItem3.setText("ShaadyEmad");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id_details_extractor/github copy.jpg"))); // NOI18N
        jMenuItem4.setText("ShaadyEmad");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id_details_extractor/linkedin copy.png"))); // NOI18N
        jMenuItem5.setText("ShaadyEmad");
        jMenu2.add(jMenuItem5);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String birth_year_1;
    String birth_year_2;
    String birth_year;
    String birth_month;
    String birth_day;
    String government_code;
    int retirement_year;
    char century_code;
    char gender_code;
    String baby_number;
    
    private void j_baby_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_baby_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_baby_NumberActionPerformed

    private void j_date_of_retirementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_date_of_retirementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_date_of_retirementActionPerformed

    private void j_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_ageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // get id
                String id = j_ID.getText();
       
        // to access every number of id       
                for(int i=0; i<id.length(); i++){
                    char ch = id.charAt(i);
                    
        // check that ID is right by  every number be between 0 to 9 and the length of id is equal 14
                if(ch>='0' && ch<='9' && id.length() == 14){
                    j_wrong_id.setText("");
                    // get gender code
                        gender_code = id.charAt(12);
                    // check if male or female
                       if(gender_code % 2 ==0){
                          j_gender.setText("Female");
                        }
                        else{
                          j_gender.setText("Male"); 
                        }
                 
                    // get baby No.
                       baby_number = id.substring(9, 13);
                       j_baby_Number.setText(baby_number);

                    // get birth day
                        birth_day = id.substring(5,7);
                    // get birth month
                        birth_month = id.substring(3,5);
                        
                    // get century code
                       century_code = id.charAt(0);
                    // get first 2 number of birth year
                        switch(century_code){
                            case '1': birth_year_1 = "18" ; break;
                            case '2': birth_year_1 = "19" ; break;
                            case '3': birth_year_1 = "20" ; break;
                            default: j_wrong_id.setText("Please enter right ID number");
                        }
                    // get second 2 numbers of birth year
                        birth_year_2 = id.substring(1,3);
                        
                    // put date of birth
                       birth_year = birth_year_1 + birth_year_2;
                       j_date_of_birth.setText(birth_day + "/" + birth_month + "/" + birth_year);
                        
                    // put date of retirement
                       retirement_year = Integer.valueOf(birth_year) + 60;
                       j_date_of_retirement.setText(birth_day + "/" + birth_month + "/" + retirement_year);
                    
                    // calculate age
                       LocalDate birth_date = LocalDate.of(Integer.valueOf(birth_year), Integer.valueOf(birth_month), Integer.valueOf(birth_day));  
                    // obtains the current date from the system clock  
                       LocalDate current_Date = LocalDate.now();  
                    // calculates the difference betwween two dates  
                       Period period = Period.between(birth_date, current_Date);
                    // put the age
                       j_age.setText( String.valueOf(period.getYears()) + " years, " + String.valueOf(period.getMonths()) + " months, " + String.valueOf(period.getDays()) + " days");
                    
                    
                    // get government code
                        government_code = id.substring(7, 9);
                    // get century that you born in it according to government code
                        switch(government_code){
                            case "1": j_city_of_birth.setText("محافظة القاهرة"); break;
                            case "02": j_city_of_birth.setText("محافظة الأسكندرية"); break;
                            case "3": j_city_of_birth.setText("محافظة بورسعيد"); break;
                            case "04": j_city_of_birth.setText("محافظة السويس"); break;
                            case "11": j_city_of_birth.setText("محافظة دمياط"); break;
                            case "12": j_city_of_birth.setText("محافظة الدقهلية"); break;
                            case "13": j_city_of_birth.setText("محافظة الشرقية"); break;
                            case "14": j_city_of_birth.setText("محافظة القليوبية"); break;
                            case "15": j_city_of_birth.setText("محافظة كفر الشيخ"); break;
                            case "16": j_city_of_birth.setText("محافظة الغربية"); break;
                            case "17": j_city_of_birth.setText("محافظة المنوفية"); break;
                            case "18": j_city_of_birth.setText("محافظةالبحيرة"); break;
                            case "19": j_city_of_birth.setText("محافظة الإسماعلية"); break;
                            case "21": j_city_of_birth.setText("محافظة الجيزه"); break;
                            case "22": j_city_of_birth.setText("محافظة بنى سويف"); break;
                            case "23": j_city_of_birth.setText("محافظة الفيوم"); break;
                            case "24": j_city_of_birth.setText("محافظة المنيا"); break;
                            case "25": j_city_of_birth.setText("محافظة أسيوط"); break;
                            case "26": j_city_of_birth.setText("محافظة سوهاج"); break;
                            case "27": j_city_of_birth.setText("محافظة قنا"); break;
                            case "28": j_city_of_birth.setText("محافظة أسوان"); break;
                            case "29": j_city_of_birth.setText("محافظة الأقصر"); break;
                            case "31": j_city_of_birth.setText("محافظة البحر الأحمر"); break;
                            case "32": j_city_of_birth.setText("محافظة الوادي الجديد"); break;
                            case "33": j_city_of_birth.setText("محافظة مطروح"); break;
                            case "34": j_city_of_birth.setText("محافظة شمال سيناء"); break;
                            case "35": j_city_of_birth.setText("محافظة جنوب سيناء"); break;
                            case "88": j_city_of_birth.setText("خارج الجمهورية"); break; 
                            default : j_wrong_id.setText("Please enter right ID number");
                }
                }
                  else{
           j_wrong_id.setText("Please enter right ID number");
           }                
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void j_city_of_birthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_city_of_birthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_city_of_birthActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ImageIcon icon = new ImageIcon("src/id_details_extractor/Id icon.png");
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ID_Extractor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ID_Extractor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ID_Extractor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ID_Extractor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ID_Extractor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField j_ID;
    private javax.swing.JTextField j_age;
    private javax.swing.JTextField j_baby_Number;
    private javax.swing.JTextField j_city_of_birth;
    private javax.swing.JTextField j_date_of_birth;
    private javax.swing.JTextField j_date_of_retirement;
    private javax.swing.JTextField j_gender;
    private javax.swing.JLabel j_wrong_id;
    // End of variables declaration//GEN-END:variables
}
